import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faMapMarkerAlt,
  faClock,
  faEnvelope,
  faPhone,
  faWarehouse,
  faScrewdriverWrench,
  faCar,
  faScrewdriver,
  faHammer,
  faMagnifyingGlass,
  faDollarSign,
  faGasPump,
  faRoad,
  faGears,
  faInfo,
  faCamera,
} from "@fortawesome/free-solid-svg-icons";
import { faFacebookF, faXTwitter, faInstagram } from "@fortawesome/free-brands-svg-icons";

library.add(
  faMapMarkerAlt,
  faClock,
  faEnvelope,
  faPhone,
  faWarehouse,
  faScrewdriverWrench,
  faCar,
  faFacebookF,
  faXTwitter,
  faInstagram,
  faScrewdriver,
  faHammer,
  faMagnifyingGlass,
  faDollarSign,
  faGasPump,
  faRoad,
  faGears,
  faInfo,
  faCamera,
);
